/**
 * Where Proto keeps things.
 *
 * Everything the operator owns lives under one root so a host can mount a single
 * volume there and keep it. Left alone the root is the working directory, which
 * is what you want locally; set PROTO_DATA_DIR to something like /data and the
 * projects, the sweep history, the run journals and the last report all move
 * together rather than half of them surviving a redeploy.
 *
 * The distinction that matters: `out/` is a cache, it can be regenerated by
 * running a sweep. `data/` and the journals are the record, and losing them
 * means the watch starts again from nothing and every baseline resends.
 */
import { join } from 'node:path'

const ROOT = process.env.PROTO_DATA_DIR ?? '.'

/** Projects, rosters, schedules and alert settings. The record. */
export const DATA_DIR = join(ROOT, 'data')
export const PROJECTS_DIR = join(DATA_DIR, 'projects')
export const HISTORY_DIR = join(DATA_DIR, 'history')
export const ACTIVE_POINTER = join(DATA_DIR, 'active.json')

/** In flight runs, so a killed sweep resumes. Also the record. */
export const STATE_DIR = process.env.PROTO_STATE_DIR ?? join(ROOT, '.proto-state')

/** The last completed report. A cache: a sweep rebuilds it. */
export const OUT_DIR = join(ROOT, 'out')
export const FINDINGS_FILE = join(OUT_DIR, 'findings.json')
